name: Push to GitHub Packages

on:
  push:
    branches:
      - main
    
jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest

    steps:
#    - name: Retag Docker image for GitHub Packages
 #     run: docker tag zaariel91/prover:v1.0 ghcr.io/zaariel91/test_prover/prover:v1.0

    - name: Log in to GitHub Packages
      run: docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_PASSWORD }}

    - name: Push Docker image to GitHub Packages
      run: docker push prover
