name: Build and Push Docker Image to GitHub Packages

on:
  push:
    branches:
      - main
    tags:
      - "v*.*"

jobs:
  build:
    name: Docker images for ghcr.io
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE_BASE: ${{ github.repository }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      # API

      - name: API image tags & labels
        id: prover
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}-prover

      - name: API image build & push
        uses: docker/build-push-action@v3
        with:
          context: /home/zaariel/stone-prover
          file: Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.prover.outputs.tags }}
          labels: ${{ steps.prover.outputs.labels }}
